- name: Create AdGuard Home directories
  ansible.builtin.file:
    path: '{{ item }}'
    recurse: true
    mode: '0644'
  loop:
    - '{{ adguard_config_dir }}'
    - '{{ adguard_data_dir }}'

- name: Copy AdGuard Home configuration file
  when: adguard_config_file | length > 0
  ansible.builtin.copy:
    src: '{{ adguard_config_file }}'
    dest: '{{ adguard_config_dir }}/AdGuardHome.yaml'
    mode: '0644'
  notify: Restart AdGuard Home container

- name: Create AdGuard Home Docker container (without DHCP server)
  when: not adguard_enable_dhcp
  community.docker.docker_container:
    name: '{{ adguard_container_name }}'
    image: 'adguard/adguardhome:{{ adguard_version }}'
    state: started
    restart_policy: always
    volumes:
      - '{{ adguard_config_dir }}:/opt/adguardhome/conf'
      - '{{ adguard_data_dir }}:/opt/adguardhome/work'
    ports:
      - '53:53/tcp'
      - '68:68/tcp'
      - '80:80/tcp'
      - '443:443/tcp'
      - '853:853/tcp'
      - '3000:3000/tcp'
      - '5443:5443/tcp'
      - '53:53/udp'
      - '443:443/udp'
      - '784:784/udp'
      - '853:853/udp'
      - '5443:5443/udp'
      - '8853:8853/udp'
  notify: Restart AdGuard Home container

- name: Create AdGuard Home Docker container (with DHCP server)
  when: adguard_enable_dhcp
  community.docker.docker_container:
    name: '{{ adguard_container_name }}'
    image: 'adguard/adguardhome:{{ adguard_version }}'
    state: started
    restart_policy: always
    volumes:
      - '{{ adguard_config_dir }}:/opt/adguardhome/conf'
      - '{{ adguard_data_dir }}:/opt/adguardhome/work'
    network_mode: host
  notify: Restart AdGuard Home container
