- name: Restart AdGuard Home container
  community.docker.docker_container:
    name: "{{ adguard_container_name }}"
    state: started
    restart: true
  notify: Wait for AdGuard Home to start

- name: Wait for AdGuard Home to start
  ansible.builtin.wait_for:
    port: "80"
    delay: 10
    timeout: 60
